---
- name: Install the libpam-google-authenticator package
  ansible.builtin.apt:
    name: "libpam-google-authenticator"
    update_cache: yes
    state: present

- name: Copy over Preconfigured GoogleAuthenticator config
  copy:
    src: google_authenticator
    dest: /home/bender/.google_authenticator
    owner: bender
    group: bender
    mode: '0600'

- name: Disable password authentication for SSH
  lineinfile:
    dest: "/etc/pam.d/sshd"
    regex: "@include common-auth"
    line: "#@include common-auth"

- name: Configure PAM to use GoogleAuthenticator for SSH logins
  lineinfile:
    dest: "/etc/pam.d/sshd"
    line: "auth required pam_google_authenticator.so nullok"

- name: Set KbdInteractiveAuthentication to 'yes'
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^KbdInteractiveAuthentication (yes|no)"
    line: "KbdInteractiveAuthentication yes"
    state: present

- name: Set ChallengeResponseAuthentication to Yes
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^ChallengeResponseAuthentication (yes|no)"
    line: "ChallengeResponseAuthentication yes"
    state: present

- name: Set Authentication Methods for bender, ec2-user, and ubuntu
  blockinfile:
    path: "/etc/ssh/sshd_config"
    block: |
      Match User "ec2-user,ubuntu"
          AuthenticationMethods publickey
      Match User "bender,!ec2-user,!ubuntu"
          AuthenticationMethods publickey,keyboard-interactive
    state: present
  notify: "Restart SSH Server"