---
- name: Create group "developers"
  group:
    name: developers
    state: present

- name: Grant developers root
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "%developers ALL=(ALL) ALL"
    create: yes

- name: Disable password prompt for sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "%developers ALL=(ALL) NOPASSWD: ALL"
    create: yes

  
- name: Create user 'bender'
  user:
    name: bender
    shell: /bin/bash
    # password: "!QAZ2wsx3edc4rfv"

- name: Add 'bender' to the 'developers' group
  user:
    name: bender
    groups: developers
    append: yes

- name: Stop sshd service
  command: sudo systemctl stop sshd

- name: Start sshd service
  command: sudo systemctl start sshd
  
- name: Create a directory named 'engineering'
  file:
    path: /opt/engineering
    state: directory
    mode: 0750
    group: developers
  
- name: Create a file in the engineering directory
  file:
    path: "/opt/engineering/private.txt"
    state: touch
    mode: 0770
    group: developers
