---
- name: Install python3-flask, gunicorn3
  ansible.builtin.apt:
    name:
      - python3-flask
      - gunicorn
      - nginx

- name: Copy Flask Sample Application
  copy:
    src: "./{{ item }}"
    dest: "/opt/engineering/{{ item }}"
    group: developers
    mode: '0750'
  loop:
    - greeting.py
    - wsgi.py

- name: Copy systemd Unit file for Greetingpip
  copy:
    src: "greeting.service"
    dest: "/etc/systemd/system/greeting.service"

- name: Start and enable Greeting Application
  systemd:
    name: greeting.service
    daemon_reload: yes
    state: started
    enabled: yes